mod.id = "handytools"
mod.name = "Handy Tools"
mod.group = "me.ez.handytools"
mod.version = "1.0.0"

["26.1.2"]
mod.mc_compat = "[26.1, 26.1.2]"
mod.mc_releases = ["26.1", "26.1.1", "26.1.2"]
deps.neo_loader = "26.1.2.108"
