modLoader="javafml"
loaderVersion="[1,)"
license="All rights reserved"
issueTrackerURL="https://github.com/igu1/"

[[mods]]
modId="handytools"
logoFile="logo.png"
version="${file.jarVersion}"
displayName="Handy Tools"
authors="Love, Cheese By Ez"
description='''
   Small punchy tools: path roller, redstone signal meter and a filtered hopper.
'''

[[dependencies.handytools]]
modId="neoforge"
type="required"
versionRange="[26.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.handytools]]
modId="minecraft"
type="required"
versionRange="[26.1,26.1.2]"
ordering="NONE"
side="BOTH"
